# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

apt_packages:
  - libhdf5-7

bioc_packages:
  - GenomeInfoDbData
  - DESeq2
  - MAST
  - S4Vectors
  - SummarizedExperiment
  - SingleCellExperiment

r_github_packages:
  - mojaveazure/loomR  

warnings_are_errors: false
