# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

os:
  - linux
  - osx

r:
  - release
  - devel

matrix:
  exclude:
    - os: osx
      r: devel

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

bioc_packages:
  - GenomeInfoDbData
  - DESeq2
  - MAST
  - S4Vectors
  - SummarizedExperiment
  - SingleCellExperiment

r_github_packages:
  - mojaveazure/loomR

warnings_are_errors: false

