# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

os:
  - linux
  - osx

r: release

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export RETICULATE_PYTHON="$HOME/miniconda/bin/python"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - pip install --upgrade pip
  - pip install phate

bioc_packages:
  - GenomeInfoDbData
  - DESeq2
  - MAST
  - S4Vectors
  - SummarizedExperiment
  - SingleCellExperiment

r_github_packages:
  - mojaveazure/loomR
  - KrishnaswamyLab/phateR

warnings_are_errors: false

