# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language:
  - r
  - python
python: 3.5
sudo: required
cache: packages

os:
  - linux
  - osx

r: release

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - pip3 install phate

bioc_packages:
  - GenomeInfoDbData
  - DESeq2
  - MAST
  - S4Vectors
  - SummarizedExperiment
  - SingleCellExperiment

r_github_packages:
  - mojaveazure/loomR
  - KrishnaswamyLab/phateR

warnings_are_errors: false

